-- ============================================================
-- DROP ALL VIEWS
-- ============================================================
DROP VIEW V_COMPANEROS_TODOS_CURSOS;

-- ============================================================
-- DROP ALL TRIGGERS
-- ============================================================
DROP TRIGGER TRG_UNIDAD_ACADEMICA;
DROP TRIGGER INSCRIPCION_LIMIT_ACTIVAS_INS;
DROP TRIGGER INSCRIPCION_LIMIT_ACTIVAS_UPD;
DROP TRIGGER ASIGNACION_NO_CURSAR_CERRADA;
DROP TRIGGER ASIGNACION_VALIDAR_NOTA_ZONA_INS;
DROP TRIGGER ASIGNACION_VALIDAR_NOTA_ZONA_UPD;
DROP TRIGGER INSCRIPCION_VERIFICAR_CIERRE_CARRERA;
DROP TRIGGER ASIGNACION_ACTUALIZAR_PROMEDIO;

-- ============================================================
-- DROP ALL FUNCTIONS
-- ============================================================
DROP FUNCTION FN_CUMPLE_REQUISITOS;
DROP FUNCTION FN_CUMPLE_REQUISITOS_CREDITOS;
DROP FUNCTION FN_VALIDAR_NOTA_ZONA;
DROP FUNCTION FN_SUMAR_CREDITOS;

-- ============================================================
-- DROP ALL TABLES (hijo → padre)
-- ============================================================
DROP TABLE HORARIO      CASCADE CONSTRAINTS;
DROP TABLE ASIGNACION   CASCADE CONSTRAINTS;
DROP TABLE PRERREQUISITO CASCADE CONSTRAINTS;
DROP TABLE PENSUM       CASCADE CONSTRAINTS;
DROP TABLE INSCRIPCION  CASCADE CONSTRAINTS;
DROP TABLE SECCION      CASCADE CONSTRAINTS;
DROP TABLE PLAN         CASCADE CONSTRAINTS;
DROP TABLE SALON        CASCADE CONSTRAINTS;
DROP TABLE CARRERA      CASCADE CONSTRAINTS;
DROP TABLE UNIDAD_ACADEMICA CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO     CASCADE CONSTRAINTS;
DROP TABLE DOCENTE      CASCADE CONSTRAINTS;
DROP TABLE CURSO        CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTE   CASCADE CONSTRAINTS;
DROP TABLE PERIODO      CASCADE CONSTRAINTS;
DROP TABLE DIA          CASCADE CONSTRAINTS;
DROP TABLE JORNADA      CASCADE CONSTRAINTS;

-- ============================================================
-- DROP ALL SEQUENCES
-- ============================================================
DROP SEQUENCE SEQ_UNIDAD_ACADEMICA;
