-- UNIDAD ACADEMICA
INSERT ALL
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (1, 'Escuela Técnica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (2, 'Escuela de Estudios de Postgrado')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (3, 'Escuela de Ciencias')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (4, 'Escuela de Ingeniería Civil')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (5, 'Escuela de Ingeniería Química')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (6, 'Escuela de Ingeniería Mecánica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (7, 'Escuela de Ingeniería Mecánica Eléctrica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (8, 'Escuela de Ingeniería Mecánica Industrial')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (9, 'Escuela de Ingeniería en Industrias Agropecuarias y Forestales')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (10, 'Escuela de Ingeniería en Ciencias y Sistemas')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (11, 'Escuela Regional de Ingeniería Sanitaria y Recursos Hidráulicos - ERIS')
SELECT 1 FROM DUAL;

SELECT * FROM unidad_academica;

-- CARRERAS FACULTAD INGENIERI
INSERT ALL
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (1, 'Ingeniería Civil', 4)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (2, 'Ingeniería Química', 5)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (3, 'Ingeniería Mecánica', 6)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (4, 'Ingeniería Eléctrica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (5, 'Ingeniería Industrial', 8)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (6, 'Ingeniería Mecánica Eléctrica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (7, 'Ingeniería Mecánica Industrial', 8)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (9, 'Ingeniería en Ciencias y Sistemas', 10)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (13, 'Ingeniería Electrónica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (35, 'Ingeniería Ambiental', 5)
SELECT 1 FROM DUAL;

SELECT * FROM carrera;

-- ESTUDIANTES DE LA UNIVERSIDA
INSERT ALL
    INTO ESTUDIANTE VALUES (9516085, 'HERNAN RICARDO AVILA CASTILLO', 3500.00, DATE '1995-03-15')
    INTO ESTUDIANTE VALUES (200011036, 'MORSE IVAN MENDEZ GONZALEZ', 4200.00, DATE '1982-07-20')
    INTO ESTUDIANTE VALUES (201407049, 'HENRY ALEXANDER GARCÍA MONTÚFAR', 3800.00, DATE '1996-11-05')
    INTO ESTUDIANTE VALUES (201513722, 'RONY ORLANDO TOHÓN LÓPEZ', 3000.00, DATE '1997-02-10')
    INTO ESTUDIANTE VALUES (201513731, 'RONY ALEJANDRO TOHÓN LÓPEZ', 3100.00, DATE '1998-06-18')
    INTO ESTUDIANTE VALUES (201602929, 'SEBASTIÁN GÓMEZ LAVARREDA', 4500.00, DATE '1998-09-12')
    INTO ESTUDIANTE VALUES (201700568, 'JONATHAN JOSUÉ ARGUETA SALAZAR', 2800.00, DATE '1999-04-22')
    INTO ESTUDIANTE VALUES (201700747, 'DENNIS ALEXANDER GAMBOA STOKES', 5200.00, DATE '1999-01-30')
    INTO ESTUDIANTE VALUES (201700866, 'ERICK NOE GÓMEZ LÓPEZ', 2700.00, DATE '1999-08-14')
    INTO ESTUDIANTE VALUES (201700870, 'ROBERTO ENRIQUE CALVILLO HERNANDEZ', 3300.00, DATE '1998-12-01')
    INTO ESTUDIANTE VALUES (201701078, 'BYRON JOSUÉ PAR RANCHO', 2900.00, DATE '1999-10-10')
    INTO ESTUDIANTE VALUES (201708880, 'BISMARCK ESTUARDO ROMERO LEMUS', 6000.00, DATE '1999-03-08')
    INTO ESTUDIANTE VALUES (201708997, 'LIZZ ANDREA MORELIA CASTELLANOS SALAZAR', 4800.00, DATE '2000-05-19')
    INTO ESTUDIANTE VALUES (201710130, 'KEVIN ESTUARDO SOTOJ GARCÍA', 2600.00, DATE '1999-07-25')
    INTO ESTUDIANTE VALUES (201801300, 'SELIM IDAIR ERGON CASTILLO', 4100.00, DATE '2000-02-11')
    INTO ESTUDIANTE VALUES (201801391, 'LUIS FERNANDO GÓMEZ RENDÓN', 3700.00, DATE '2000-06-30')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO ESTUDIANTE VALUES (201801500, 'CARLOS ANDRÉS PÉREZ LÓPEZ', 3200.00, DATE '2000-04-12')
    INTO ESTUDIANTE VALUES (201802345, 'MARIA FERNANDA GONZALEZ RUIZ', 4500.00, DATE '2000-08-21')
    INTO ESTUDIANTE VALUES (201803678, 'JOSÉ LUIS MARTÍNEZ HERNÁNDEZ', 3800.00, DATE '1999-12-10')
    INTO ESTUDIANTE VALUES (201804123, 'ANA SOFÍA RAMÍREZ MORALES', 5200.00, DATE '2001-03-05')
    INTO ESTUDIANTE VALUES (201805987, 'LUIS FERNANDO CASTILLO ORTIZ', 2900.00, DATE '2000-07-18')
    
    INTO ESTUDIANTE VALUES (201901234, 'DIEGO ALEJANDRO RODRÍGUEZ PÉREZ', 4100.00, DATE '2001-09-14')
    INTO ESTUDIANTE VALUES (201902567, 'KAREN ELIZABETH LÓPEZ GARCÍA', 3600.00, DATE '2001-01-30')
    INTO ESTUDIANTE VALUES (201903890, 'MARIO ESTUARDO HERNÁNDEZ VÁSQUEZ', 4700.00, DATE '2000-11-22')
    INTO ESTUDIANTE VALUES (201904321, 'PAOLA ANDREA FLORES MÉNDEZ', 3900.00, DATE '2001-05-09')
    INTO ESTUDIANTE VALUES (201905654, 'JAVIER ENRIQUE CRUZ GÓMEZ', 3300.00, DATE '2000-02-17')
    
    INTO ESTUDIANTE VALUES (202001111, 'ANDREA CAROLINA AGUILAR RUIZ', 5000.00, DATE '2002-06-25')
    INTO ESTUDIANTE VALUES (202002222, 'OSCAR DANIEL MORALES PÉREZ', 2800.00, DATE '2002-10-12')
    INTO ESTUDIANTE VALUES (202003333, 'FERNANDO JOSUÉ SANTOS LÓPEZ', 4200.00, DATE '2001-07-03')
    INTO ESTUDIANTE VALUES (202004444, 'GLORIA ESTEFANÍA VELÁSQUEZ CASTRO', 4600.00, DATE '2002-03-19')
    INTO ESTUDIANTE VALUES (202005555, 'SERGIO ANTONIO RAMOS HERNÁNDEZ', 3700.00, DATE '2001-12-08')
    
    INTO ESTUDIANTE VALUES (202101111, 'DAVID ALEJANDRO ORTIZ MORALES', 3400.00, DATE '2003-01-27')
    INTO ESTUDIANTE VALUES (202102222, 'LUCÍA FERNANDA PÉREZ GARCÍA', 4800.00, DATE '2003-04-11')
    INTO ESTUDIANTE VALUES (202103333, 'JORGE LUIS CASTRO RAMÍREZ', 3900.00, DATE '2002-09-29')
    INTO ESTUDIANTE VALUES (202104444, 'MÓNICA ANDREA GUTIÉRREZ FLORES', 4100.00, DATE '2003-06-14')
    INTO ESTUDIANTE VALUES (202105555, 'CARLOS ENRIQUE TORRES MARTÍNEZ', 3600.00, DATE '2002-02-06')
    
    INTO ESTUDIANTE VALUES (202201111, 'ROBERTO ALEJANDRO DÍAZ LÓPEZ', 3000.00, DATE '2004-08-18')
    INTO ESTUDIANTE VALUES (202202222, 'VALERIA SOFÍA HERRERA CRUZ', 5200.00, DATE '2004-05-21')
    INTO ESTUDIANTE VALUES (202203333, 'EDWIN JOSUÉ MORALES CASTILLO', 3100.00, DATE '2003-11-30')
    INTO ESTUDIANTE VALUES (202204444, 'PAOLA GABRIELA RUIZ AGUILAR', 4700.00, DATE '2004-03-12')
    INTO ESTUDIANTE VALUES (202205555, 'JULIO CESAR PÉREZ RAMÍREZ', 3500.00, DATE '2003-07-07')
    
    INTO ESTUDIANTE VALUES (202301111, 'ESTEBAN ALEJANDRO GARCÍA TORRES', 4400.00, DATE '2005-01-10')
    INTO ESTUDIANTE VALUES (202302222, 'DANIELA FERNANDA LÓPEZ MORALES', 3900.00, DATE '2005-09-23')
    INTO ESTUDIANTE VALUES (202303333, 'HUGO ANTONIO VÁSQUEZ HERNÁNDEZ', 2800.00, DATE '2004-12-15')
    INTO ESTUDIANTE VALUES (202304444, 'KARLA ELIZABETH CASTILLO PÉREZ', 4600.00, DATE '2005-06-04')
    INTO ESTUDIANTE VALUES (202305555, 'JORGE EDUARDO CRUZ GÓMEZ', 3700.00, DATE '2004-02-28')
    
    INTO ESTUDIANTE VALUES (202306666, 'MIGUEL ÁNGEL MARTÍNEZ LÓPEZ', 3300.00, DATE '2005-10-19')
    INTO ESTUDIANTE VALUES (202307777, 'ANA PAULA GONZÁLEZ RAMÍREZ', 4800.00, DATE '2005-07-13')
    INTO ESTUDIANTE VALUES (202308888, 'LUIS ALBERTO HERRERA MORALES', 3100.00, DATE '2004-11-02')
    INTO ESTUDIANTE VALUES (202309999, 'SOFÍA ANDREA PÉREZ CASTRO', 5000.00, DATE '2005-03-26')
    INTO ESTUDIANTE VALUES (202310000, 'RAÚL ESTUARDO FLORES DÍAZ', 3500.00, DATE '2004-08-09')
SELECT 1 FROM DUAL;

SELECT * FROM estudiante;

-- DOCENTES
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6043, 'BRIAN JOS� JIM�NEZ	MART�NEZ', 7821);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3660, 'PABLO GERARDO SCHAART CALDER�N', 8268);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4595, 'CARLOS ALBERTO NAVARRO FUENTES', 9272);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1968, 'MIGDALIA AZUCENA DEL CID', 9586);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1188, 'OSWALDO ROMEO ESCOBAR ALVAREZ', 5856);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2599, 'FERNANDO JOS� PAZ GONZ�LEZ', 8766);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2521, 'INGRID LORENA BENITEZ PACHECO', 8445);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1989, 'HILDA FABIOLA ESPA�A GIR�N', 5993);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6089, 'JULIO ALFREDO FERN�NDEZ RODR�GUEZ', 5220);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1077, 'MARIA DEL MAR GIRON CORDON', 7980);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9453, 'MIGUEL VENTURA PEREZ', 6214);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9338, 'SILVIA CAROLINA LEMUS CASTRO', 9804);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4688, 'MAYRA VIRGINIA CARVAJAL CASTILLO', 8454);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3468, 'ENDOR STEVE ORTIZ DEL CID', 5253);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8882, 'SILVIA PATRICIA HURTARTE HERNANDEZ', 5723);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8426, 'HELEN ROCIO RAMIREZ LUCAS', 9037);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8712, 'KEVIN JOSUE SANTOS SALAZAR', 5744);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8271, 'RAMIRO AUGUSTO SANTIZO GONZALEZ', 7198);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5040, 'ANA RUFINA HERRERA SOTO', 6870);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5801, 'MARCO ANTONIO TAX ALVAREZ', 7038);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3316, 'JUAN ORLANDO LOPEZ OROZCO', 5334);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6846, 'ISMAEL HOMERO JEREZ GONZALEZ', 5836);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5468, 'RENATO GIOVANNI PONCIANO SANDOVAL', 9125);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3979, 'ILEANA GUISELA RALDA R. DE ILLESCAS', 9000);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1066, 'PABLO REN� LE�N MARQUEZ', 8417);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1201, 'JOSUE MANUEL QUIJIVIX COTI', 8425);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8315, 'JAVIER ANTONIO CER�N ROSALES', 9796);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3276, 'WALTER JACOBO GALICIA GARCIA', 6494);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2588, 'JURGEN ANDONI RAMIREZ RAM�REZ', 8513);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9352, 'INGRID SALOME RODRIGUEZ DE LOUKOTA', 8269);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6395, 'ELMER DIONICIO SUC CHOCOOJ', 5913);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3275, 'ERICK DANIEL POR�N MU�OZ', 9941);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1808, 'GABRIEL ESTUARDO SOL�RZANO CASTELLANOS', 7334);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7023, 'LUIS MARIANO ALVAREZ MURALLES', 6372);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7545, 'JORGE PABLO ORTIZ SOTO', 8733);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8611, 'LUIS GREGORIO ALFARO VELIZ', 6762);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3758, 'ROGELIO ALFREDO SALAZAR DE LEON', 8783);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7888, 'LUIS ALFREDO ASTURIAS ZUNIGA', 5927);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1337, 'DOUGLAS KENEDY ROMAN AVILA', 5413);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9314, 'WILLIAM EDUARDO FAGIANI CRUZ', 5981);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6187, 'PABLO FERNANDO SANTOS SAMAYOA', 6707);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8724, 'PEDRO RAFAEL MORAN ARAGON', 8709);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9701, 'JOSE ANIBAL SILVA DE LOS ANGELES', 8790);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1849, 'CARLOS ALBERTO ARIAS LARA', 8509);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7974, 'JULIO ROLANDO BARRIOS ARCHILA', 8135);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2865, 'SIGRID ALITZA CALDERON DE LEON', 7434);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2691, 'ERWIN MANUEL ORTIZ CASTILLO', 8745);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3798, 'CARLOS ENRIQUE PINTO ALONZO', 7529);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2328, 'LUIS EDUARDO MONROY P�REZ', 9890);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9004, 'OSMAR BERNAL GODINEZ VEL�SQUEZ', 8568);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7918, 'EDGAR ESTUARDO SANTOS SUTUJ', 9379);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9062, 'CESAR ERNESTO URQUIZU RODAS', 9673);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4690, 'GERSON JONATAN RAMIREZ BACH', 5058);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8799, 'JORGE RODOLFO GARCIA CARRERA', 8729);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7788, 'LUIS CESAR LIZAMA QUI�ONEZ', 7024);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9045, 'KEVIN RA�L POZUELOS ESTRADA', 7696);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5752, 'ERIC RONALDO RUIZ MATIAS', 9973);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9156, 'JORGE ESTUARDO PUMAY SOY', 5419);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7549, 'ALBERTO KANEC IXCHOP ORDO�EZ', 8899);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9767, 'DIANA ORALIA SALGUERO ESPANA', 8909);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9647, 'RICARDO ENRIQUE CONTRERAS FOLGAR', 7802);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5361, 'JENS JEREMY PABLO SOSOF', 7285);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1240, 'OSCAR ALBERTO MARTINEZ LOBOS', 5800);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2859, 'HUGO LEONEL MONTENEGRO FRANCO', 6746);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9400, 'JULIO C�SAR VILLATORO SANABRIA', 8981);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2130, 'ANA PAOLA M�NDEZ DE LE�N', 8660);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4519, 'CARLOS FERNANDO ENRIQUE LOPEZ GARCIA', 8097);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2876, 'ALVARO OBRAYAN HERN�NDEZ GARC�A', 8493);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5990, 'ALEX EVELIO CASTA�EDA SALAZAR', 9747);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9524, 'JOS� RODRIGO DE LE�N VEL�SQUEZ', 8336);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8056, 'LUDWING FEDERICO ALTAN SAC', 9989);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2829, 'NATALIE GIULIANA ECHEVERRIA CHANG', 5507);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8712, 'MIRIAM PATRICIA RUBIO CONTRERAS DE AKU', 6324);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9831, 'RIGOBERTO RAFAEL SANDOVAL LOPEZ', 9476);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2485, 'CLAUDIO CESAR CASTA�ON CONTRERAS', 5028);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5147, 'SORAYA DEL ROSARIO MARTINEZ SUM', 6529);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6990, 'JOSE MARIA SAQUIMUX CANASTUJ', 9378);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4251, 'JUAN CARLOS GODINEZ OROZCO', 8294);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9567, 'ANA MAR�A NAVARRO  OROZCO', 6055);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3030, 'CARLOS ALFREDO ANGULO HUERGO', 9492);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9587, 'CARLOS ANDRES P�REZ TORRES', 9026);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6570, 'SERGIO ALEJANDRO RECINOS', 5411);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4080, 'PEDRO PABLO HERNANDEZ RAMIREZ', 5805);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8411, 'LUIS MARTINOLY GODINEZ OROZCO', 6842);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1517, 'CALIXTO SANTIAGO MONTEAGUDO CORDERO', 5589);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1379, 'MOISES EDUARDO VELASQUEZ OLIVA', 6114);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7073, 'LESBIA CAROLINA CARRANZA ESCOBAR', 8352);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5099, 'JOAB ISRAEL AJSIVINAC AJSIVINAC', 5183);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7873, 'ESTUARDO AUGUSTO GARRIDO CHINCHILLA', 5819);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1134, 'MARCOS NERY SALAZAR', 8264);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7568, 'BAYRON ARMANDO CUYAN CULAJAY', 9117);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3996, 'CRISTOBAL MARDOQUEO ARRIOLA MAIREN', 5359);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6040, 'WENDY NORA MIRANDA LOPEZ', 5498);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7754, 'KARINA NOHEMI RAMIREZ ORELLANA', 5812);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2055, 'EDGAR FRANCISCO RODAS ROBLEDO', 6219);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4439, 'SERGIO LEONEL GOMEZ BRAVO', 6718);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5886, 'EDGAR HAROLDO TORRES SOTO', 9614);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8797, 'ERIC JOSUE JACOBS MAZARIEGOS', 8741);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5792, 'JOSE MAURICIO ARRIOLA DONIS', 7349);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5101, 'MISHELLE ESTEFANNY CARDONA HERNANDEZ', 8337);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3926, 'DIEGO JOSUE GUEVARA ABAJ', 5650);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2103, 'DOMINIC JUAN PABLO RUANO PEREZ', 9047);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2214, 'DENNIS ANDR� GONZ�LEZ FLORES', 7894);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9754, 'JOHAN ESTIVEN SAB�N L�PEZ', 8059);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7869, 'JORGE LUIS ALVAREZ MEJIA', 7840);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3879, 'JOS� MANUEL MORO BLANCO', 7880);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5903, 'KENNETH LUBECK CORADO ESQUIVEL', 8575);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4125, 'ROCIO CAROLINA MEDINA GALINDO', 9091);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4583, 'RAMON BENJAMIN PIEDRASANTA BATZ', 9758);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7470, 'KHRISTIAN MANOLO JUNIOR GARC�A PINEDA', 9223);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3923, 'TONY YOBANY BARRERA DONIS', 7593);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7231, 'ROBERTO MIGUEL GARC�A SANTIZO', 8416);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6275, 'WUILLIAN RICARDO YON CHAVARRIA', 5815);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6425, 'LUIS EDUARDO PORTILLO ESPA�A', 6891);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6054, 'LAURA ROSMERY BRIONES ZELADA', 7641);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7058, 'FREIRY JAVIER GRAMAJO LOPEZ', 6323);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7016, 'OTTO LEONEL SU�REZ MOTA', 5393);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3639, 'RENATO ISAAC RIVERA PEREZ', 7364);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7284, 'SHARONN PRYSCILA PU MORALES', 8161);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4297, 'ELDER OBDULIO CALDER�N NAVARIJO', 6762);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9080, 'LUIS EDUARDO DURAN CORDOVA', 5065);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3427, 'JUAN PABLO SAMAYOA RU�Z', 6945);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3858, 'CARLOS ANTONIO CAJAS VIDAURRE', 6941);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9372, 'ANA VELA CASTRO MELLADO', 5826);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6664, 'JOSE ROLANDO CHAVEZ SALAZAR', 6611);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8651, 'UZZI LIBNI AARON PINEDA SOLORZANO', 7073);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2472, 'JAVIER ALEJANDRO AVILA FLORES', 7940);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5353, 'TELMA MARICELA CANO MORALES', 5546);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8696, 'JOSE DANIEL EL�AS TEJAXUN SAY', 7758);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5698, 'NESTOR OBDULIO ALEJANDRO CHAMALE CHITIC', 7067);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8929, 'RIVER ANDERSON ISMALEJ ROMAN', 6520);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4213, 'WILLIAM ESTUARDO ESCOBAR ARGUETA', 9954);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6175, 'LUIS ADOLFO DE LEON GOMEZ', 7506);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3824, 'SINDY MASSIEL GODINEZ BAUTISTA', 5049);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9261, 'OTTO AMILCAR RODRIGUEZ ACOSTA', 9540);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7866, 'ADELA MARIA MARROQUIN GONZALEZ', 9070);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1915, 'STAFF', 5677);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7611, 'VICTOR MANUEL MONZON VALDEZ', 5039);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2378, 'HELEN JEANNETH MARTINEZ SUM', 7696);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5026, 'MARIA ALEJANDRA MA VILLATORO', 7911);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7655, 'MARIO ESTUARDO ARRIOLA AVILA', 8254);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5077, 'GERARDO ORDONEZ', 8118);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9817, 'ALEJANDRO ESTRADA MARTINEZ', 8977);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6271, 'FRANCISCO ABEN ROSALES CEREZO', 8655);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9330, 'JOSE FERNANDO SAMAYOA ROLDAN', 9856);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6684, 'RONAL NOE GALVEZ GARCIA', 5069);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3713, 'OTTO FERNANDO ANDRINO GONZALEZ', 9897);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4208, 'MAYRA REBECA GARCIA SORIA DE SIERRA', 6545);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5429, 'HERBERT SAMUEL FIGUEROA AVENDA�O', 8384);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7559, 'ALAN GIOVANI COSILLO PINTO', 7517);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5634, 'JOSE ALFREDO GONZALEZ DIAZ', 8087);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1913, 'GLADYS MAR�A ESTRADA QUINTANILLA', 7884);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2708, 'CARLOS EDUARDO GUZMAN SALAZAR', 9559);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2906, 'BRIAN  ENRIQUE CHICOL  MORALES', 5921);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5140, 'NOEL JOEL GRAMAJO MONTERROSO', 5668);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9123, 'JUAN ALBERTO ORTIZ ESTURBAN', 8125);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6141, 'PABLO JOS� OLIVA BONILLA', 5597);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7855, 'OSCAR EDUARDO MORALES GIR�N', 6217);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7130, 'MAYRA SAADETH ARREAZA MARTINEZ', 9565);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3798, 'LUIS ALBERTO VETTORAZZI ESPANA', 9345);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5509, 'ROCIO LASSALETTE VAQUIAX REYES', 7667);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1505, 'DIEGO JOSE PORRES ALMEDA', 6700);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2336, 'AURELIA ANABELA CORDOVA ESTRADA', 9353);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2766, 'ERICK GEOVANI AGUSTIN MARROQUIN', 8038);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8605, 'MELYZA ALEJANDRA RODRIGUEZ CONTRERAS', 8817);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9813, 'DILMA YANET MEJICANOS JOL', 5495);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1189, 'LUIS ALBERTO ARIAS SOL�RZANO', 7635);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4600, 'CARLOS RODOLFO MARTINEZ GIRON', 7589);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3070, 'WALTER ROLANDO SALAZAR GONZ�LEZ', 7005);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3069, 'CARLOS ALFREDO AZURDIA MORALES', 9838);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7146, 'TOBIAS RAFAEL ZAMORA SANTOS', 9802);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8060, 'DIEGO ANDRES HUITE ALVAREZ', 6586);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3453, 'GUILLERMO ANTONIO PUENTE ROMERO', 6112);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3466, 'JULIO RICARDO DIAZ PAPPA', 6407);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8401, 'DANILO ESCOBAR CORONADO', 6673);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8173, 'HELMUNT FEDERICO CHICOL CABRERA', 6822);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1605, 'OSCAR HUMBERTO MONTES ESTRADA', 8608);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3826, 'JORGE LUIS PEREZ RIVERA', 8035);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3528, 'KAREN LUCRECIA HURTARTE PINEDA', 8519);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5026, 'CESAR ARIEL VILLELA RODAS', 6884);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7494, 'MARIO JOSE MERIDA MERE', 5393);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6237, 'ALLEN EDUARDO RAMIREZ TOLEDO', 6911);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2409, 'JOSE ALFREDO AGUILAR CHAMALE', 5871);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1738, 'WALTER GIOVANNI ALVAREZ MARROQUIN', 6518);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8610, 'CHRISTIAN ANTONIO ORELLANA L�PEZ', 9072);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1379, 'NERY AMILCAR MEJIA GODINEZ', 8147);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1977, 'EMMETT ECHEVERRIA VALENZUELA', 8706);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3619, 'MAR�A LORENA RIZZO L�PEZ', 6685);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7658, 'DABNEY IVAN MENDOZA CENTENO', 7953);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8869, 'EDGAR YANUARIO LAJ HUN', 6940);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8130, 'ANA GLORIA MONTES PE�A', 7031);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5306, 'ESDRAS FELICIANO MIRANDA OROZCO', 8199);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7896, 'BYRON GERARDO CHOCOOJ BARRIENTOS', 6703);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1758, 'DANIEL EDUARDO MELLADO AYALA', 5477);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4836, 'LUIS EDUARDO CORONADO NOJ', 7386);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2616, 'JOSE ADOLFO TUNA AGUILAR', 5174);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7538, 'LUIS ANTONIO CASTILLO JAVIER', 8343);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2431, 'BRYAN ALEJANDRO CASTA�ON MARTINEZ', 6766);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6895, 'EDGAR RENE ORNELIS HOIL', 6030);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4005, 'TANNIA MAGALY DE LEON MORAN', 6189);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2786, 'OSCAR APARICIO SEGURA MONZON', 7568);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4541, 'MARIO AUGUSTO L�PEZ ORDO�EZ', 9494);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8337, 'JOSE DANIEL GUZMAN HERNANDEZ', 9201);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6948, 'MILTON ALEXANDER FUENTES OROZCO', 8760);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9454, 'HUGO LEONEL TIUL VALENZUELA', 8076);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3835, 'ANGELICA BECILIA PACHECO MAZARIEGOS', 9606);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2523, 'VIVIAN DAMARIS CAMPOS GONZALEZ', 9952);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8118, 'JOS� MANUEL L�PEZ LEMUS', 7301);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8030, 'WILLIAM SAMUEL GUEVARA ORELLANA', 8142);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3358, 'SERGIO ARNALDO MENDEZ AGUILAR', 7658);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7245, 'GREYSI ILDOARA CALDERON CHAY', 6802);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5723, 'MARIO GUSTAVO LOPEZ HERNANDEZ', 6089);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9730, 'EDGAR  ESTUARDO CHAJ  RAMIREZ', 5829);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5728, 'CASTA PETRONA ZECENA ZECENA', 9135);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8730, 'CARLOS ENRIQUE G�MEZ DONIS', 8917);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3644, 'EMELINE LORENA  PAREDES SANTIZO', 5256);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3211, 'FLORIZA FELIPA AVILA PESQUERA DE MEDINILLA', 5704);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8074, 'HUGO LEONEL RAMIREZ ORTIZ', 8160);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1038, 'MARIO ERNESTO MARROQUIN PEREZ', 5977);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7594, 'DENNIS STANLEY BARRIOS GONZALEZ', 5325);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1509, 'EDWIN ESTUARDO ZAPETA GOMEZ', 9947);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3761, '�LVARO GIOVANNI LONGO MORALES', 6186);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5699, 'PABLO CESAR AN�BAL SARAVIA SOLARES', 8240);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3910, 'ALBERTO EULALIO HERNANDEZ GARCIA', 6622);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9972, 'LOIDA LISBETH CHAMAL� NI�OS', 5892);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3192, 'MYNOR ISRAEL MIRANDA L�PEZ', 7548);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6479, 'NEFTALI DE JESUS CALDERON MENDEZ', 6313);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2119, 'ALLAN GIOVANNI V�LIZ P�REZ', 8817);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3188, 'CARLOS ALBERTO GARRIDO LOPEZ', 5301);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4186, 'ERICKA JOHANA CANO DIAZ', 8760);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7769, 'JULIO ROBERTO LUNA AROCHE', 6677);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3215, 'MONICA MARLENI QUI�ONEZ ANDRADE', 5787);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3921, 'NORMAN LEONEL SIGUI GIL', 7736);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2773, 'ADOLFO NARCISO GRAMAJO ANTONIO', 8004);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7630, 'ERWIN DANILO GONZALEZ TREJO', 7604);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7633, 'MANUEL ALFREDO ARRIVILLAGA OCHAETA', 9062);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9223, 'ARMANDO GALVEZ CASTILLO', 5907);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8206, 'RONALD ESTUARDO ALVAREZ GONZ�LEZ', 6355);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7145, 'CARLOS JAVIER COX BAUTISTA', 8355);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1007, 'OSCAR ARGUETA HERNANDEZ', 8632);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5938, 'LUIS FELIPE PEREZ URIAS', 7462);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9477, 'EDWIN JOS� SARAVIA CANO', 5759);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3501, 'GUSTAVO ADOLFO SANTOS OROZCO', 8984);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6685, 'FABIOLA BEATRIZ RAMIREZ PINTO', 5317);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2092, 'JOSUE DAVID SOTOY JULAJUJ', 7532);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5750, 'HEINZ RICARDO GOMEZ GALINDO', 5599);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5549, 'NANCY MARIA GUTIERREZ SAMAYOA', 9258);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1949, 'JOSU� ALEJANDRO P�REZ BENITO', 6078);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4089, 'VIRGINIA VICTORIA TALA AYERDI', 6232);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7196, 'MARIA JOSE VEGA ORTEGA', 5989);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6523, 'DINNA LISSETTE ESTRADA MOREIRA DE ROSSAL', 5436);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3043, 'GLENDA PATRICIA GARCIA SORIA', 9861);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9249, 'DIEGO ABRAHAM ROBLES MEZA', 7958);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8052, 'KAREN NOELIA HERN�NDEZ AVILA', 6273);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8524, 'ALEX SUNTECUN CASTELLANOS', 8169);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3035, 'WALTER JAVIER SANTIZO MAZARIEGOS', 8514);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7236, 'WENDY MARISOL OROZCO MIRANDA', 7876);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4940, 'LORENA VICTORIA PINEDA CABRERA', 7275);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9780, 'GIOVANNI SAUL CONCOH� CAX', 8861);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2191, 'MYNOR FRANCISCO MOR�N GARCIA', 8470);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2986, 'MANUEL FERNANDO LOPEZ FERNANDEZ', 5593);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8416, 'YOCASTA  IVANOBLA ORTIZ DEL CID', 6043);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2757, 'ASTRID SARA� CHOX�N SAMAYOA', 5334);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6579, 'HILDA PIEDAD PALMA RAMOS', 6034);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3288, 'KENNETH ISSUR ESTRADA RUIZ', 7093);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9531, 'EDUARDO MARTIN RIVERA P�REZ', 6055);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4012, 'MATILDE LUCRECIA MARTINEZ AGUIRRE', 9057);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4215, 'CARLOS SNELL CHICOL MORALES', 6401);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9203, 'EDDY ALEJANDRO MURGA BARILLAS', 7002);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8140, 'VICTOR VINICIO BARRIOS US', 7233);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7367, 'ESTUARDO JEREZ SANTOS', 8346);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6538, 'GERSON JO�L ORTEGA MORALES', 9754);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5501, 'HERMAN IGOR VELIZ LINARES', 8098);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9821, 'MANUEL HAROLDO CASTILLO REYNA', 8612);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3438, 'H�CTOR ABDIAS MEJ�A ELIAS', 5075);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5841, 'GABRIEL ALEJANDRO DIAZ LOPEZ', 9884);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8973, 'MILDRED CATALINA HERNANDEZ ROLDAN', 6228);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6185, 'OSCAR ALEJANDRO PAZ CAMPOS', 6404);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7146, 'CARLOS GUSTAVO ALONZO', 6699);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2513, 'JOSE MARIANO GATICA HUERTAS', 8656);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7088, 'DOUGLAS JOSUE MARTINEZ HUIT', 5535);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9005, 'CARLOS AXEL FERNANDO HERN�NDEZ GONZ�LEZ', 9313);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7639, 'MERCEDES ESTHER ROQUEL CHAVEZ', 6617);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2351, 'YERVIS MAURICIO L�PEZ ESTRADA', 5810);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1615, 'LUIS  ALBERTO BAUTISTA', 8036);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6002, 'TOB�AS FRANCISCO ZAMORA SANTOS', 9762);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1486, 'LESBIA MAGALI HERRERA LOPEZ', 5253);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5796, 'JOS� ESTUARDO GALINDO ESCOBAR', 8328);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2381, 'LADY MARIEBELIA ELIAS ESTRADA', 6929);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8271, 'SILVIO JOSE RODRIGUEZ SERRANO', 9608);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8286, 'EDWIN ESTUARDO SARCE�O ZEPEDA', 5304);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5717, 'KEVIN ADIEL LAJPOP AJPACAJA', 9751);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2507, 'C�SAR FERNANDO SAZO QUISQUINAY', 8181);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1292, 'MYNOR RODERICO FIGUEROA FUENTES', 6676);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4252, 'HUGO ARMANDO POLANCO VASQUEZ', 7936);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2160, 'ARTURO RODRIGO SAMAYOA DARDON', 6349);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2049, 'HAROLD	EDUARDO ROJAS BARRIOS', 6517);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5404, 'EDGAR ROLANDO ALVAREZ RODRIGUEZ', 8471);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1035, 'JOSE MANUEL RUIZ JUAREZ', 7938);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9619, 'JUAN MIGUEL MONTEALEGRE GOMEZ', 7023);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9320, 'OWEN TORRES RIVERA', 8958);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2095, 'JOHNNY WHILLMAN ALDANA OSORIO', 8246);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6682, 'JOSE GABRIEL ORDONEZ MORALES', 6747);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3298, 'JUAN CARLOS LINARES CRUZ', 6136);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5426, 'ALLAN ALBERTO MORATAYA G�MEZ', 9600);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3956, 'JORGE MARIO SITAVI COS', 8428);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4044, 'JUAN ALVARO DIAZ ARDAVIN', 8059);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3337, 'MARCO TULIO ALDANA PRILLWITZ', 6658);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1503, 'EDGAR DARIO ALVAREZ COTI', 5656);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4241, 'JOSHUA ALEXANDER V�SQUEZ DEL AGUILA', 9693);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1020, 'DIEGO FELIPE CALI MORALES', 6526);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3761, 'OTTO ROMAN OLIVAREZ CRUZ', 9585);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5973, 'PAULO VLADEM�R ARGUETA ORTEGA', 6855);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7006, 'EDDY  JOSUE SOLARES  ESPINOZA', 9675);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7837, 'OTTO IV�N AUGUSTO OROZCO Y OROZCO', 5377);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6045, 'MAR�A DE LOS ANGELES MIRANDA DUARTE', 8949);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1829, 'DARIO FRANCISCO LUCAS MAZARIEGOS', 7485);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4545, 'CHRISTA DEL ROSARIO CLASSON REHWOLDT DE PINTO', 9871);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2512, 'JONATHAN EFREN ALVAREZ CACACHO', 9241);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2897, 'FERNANDO MISAEL MORALES ORTIZ', 6207);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4110, 'GUSTAVO BENIGNO OROZCO GODINEZ', 7840);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1338, 'MARIO RENATO ESCOBEDO MARTINEZ', 9122);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2653, 'DIANA ALEJANDRA PACAY GARC�A', 5836);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3086, 'YEFRY VALENTIN ROSALES JUAREZ', 5178);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2941, 'JORGE GILBERTO GONZALEZ PADILLA', 6806);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1385, 'MILTON LENIN HERNANDEZ GONZALEZ', 8775);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1646, 'SERGIO SEBASTI�N SANDOVAL RUIZ', 7433);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2875, 'GUIPPSY JEANNIRA MENENDEZ PEREZ', 7090);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9973, 'JACQUELIN ANDREA GARC�A FLORES', 8130);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7324, 'MARIO ENRIQUE RIVERA GONZALEZ', 5112);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6388, 'BERTHA ROXANDA MOLINA LEON DE QUINTO', 6795);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9135, 'FRANCISCO BERNARDO R DE LA ROSA', 9544);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6967, 'RODOLFO   ESTUARDO QUIROA  MELENDRES', 6255);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8357, 'LUIS ESTUARDO SARAVIA RAMIREZ', 9646);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9947, 'OSCAR GIOVANNI HERN�NDEZ CARIAS', 5352);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6559, 'ALEJANDRO CASTA�ON LOPEZ', 5613);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9109, 'RONY DANIEL HERNANDEZ GOMEZ', 6507);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6362, 'LUIS ENRIQUE IZQUIERDO OCHOA', 7044);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3377, 'MARIO JOSE BAUTISTA FUENTES', 8317);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6926, 'HUGO LEONEL ALVARADO DE LEON', 8464);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5034, 'CHRISTIAN DAVID POCOL FRANCO', 6900);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7668, 'EDER KEITH PAZ TIGUILA', 6945);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7636, 'FERNANDO AMILCAR BOITON VELASQUEZ', 7411);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1647, 'KARLA GIOVANNA JUDITH P�REZ LOARCA', 7779);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9211, 'MARCO PABLO MAZARIEGOS MACARIO', 8094);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7109, 'CARLOS SALVADOR WONG DAVI', 9261);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6043, 'KAREN NATALIE MEINICKE PALACIOS', 7059);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7508, 'JOSE ALBERTO BOY PIEDRASANTA', 6080);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2617, 'EDGAR RUBEN SABAN RAXON', 5286);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7453, 'CARLOS HUMBERTO PEREZ RODRIGUEZ', 5214);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9186, 'JUAN CARLOS CORDOVA ZECE�A', 6251);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2622, 'ANDREA SUSANA L�PEZ RAM�REZ', 6086);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5026, 'JOSSELINE GRISELDA MONTECINOS HERN�NDEZ', 8327);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6097, 'SERGIO LUIS VALD�Z P�REZ', 5442);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9576, 'PABLO ENRIQUE MORALES PANIAGUA', 7737);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1994, 'JULIO CESAR SOLARES PENATE', 9185);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2961, 'OMAR ENRIQUE MEDRANO MENDEZ', 8324);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5351, 'LUIS MANUEL SANDOVAL MENDOZA', 7686);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1535, 'SAUL CABEZAS DURAN', 8713);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6436, 'BRENDA IZABEL MIRANDA CONSUEGRA', 8207);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2116, 'WILLIAMS GUILLERMO ALVAREZ MEJIA', 7058);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1946, 'KEVIN GOLWER ENRIQUE RUIZ BARBALES', 9457);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2922, 'JORGE MIGUEL MALDONADO ACEVEDO', 7692);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1225, 'BYRON RENE AGUILAR UCK', 8289);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9885, 'ALDO OZAETA SANTIAGO', 6197);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4614, 'JAIME DOMINGO CARRANZA GONZALEZ', 5000);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2527, 'AMAHAN SANCHEZ ALVAREZ', 6562);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4313, 'EDWIN JOSUE IXPATA REYES', 7030);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7730, 'ORLANDO POSADAS VALDEZ', 9174);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2585, 'CLAUDIA LICETH ROJAS MORALES', 6090);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8424, 'SHERLY GABRIELA HERRERA ESCOBAR', 8680);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5749, 'FREDY MAURICIO MONROY PERALTA', 5112);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2185, 'ERICKA NATHALIE LOPEZ TORRES', 6693);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7071, 'CARLOS FERNANDO RODAS', 7078);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2725, 'NATANAEL JONATHAN REQUENA GOMEZ', 7133);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7104, 'NATALIA MARIEL CALDER�N ECHEVERR�A', 7002);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7540, 'NORA LEONOR GARCIA TOBAR', 6562);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7660, 'VICTOR HUGO GARCIA ROQUE', 6433);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4242, 'HAROL JOSE CARIAS DIEGUEZ', 7560);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9225, 'MARIO ALBERTO REYES CALDER�N', 6688);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9397, 'MIRNA IVONNE ALDANA LARRAZABAL', 8384);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7699, 'INGRID MARISOL FLORES ESTRADA', 6789);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2327, 'CARLA DEYANIRA GORDILLO DE MARCHENA', 5942);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9419, 'BAYRON WOSVELY LOPEZ LOPEZ', 6468);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6384, 'CESAR AUGUSTO FERNANDEZ CACERES', 6082);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1085, 'BYRON ESTUARDO SOLIS GONZALEZ', 6062);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8241, 'LUIS FERNANDO ESPINO BARRIOS', 9694);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9645, 'LIGIA EUNICE VASQUEZ DARDON', 9340);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5612, 'MURPHY OLYMPO PAIZ RECINOS', 5245);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8459, 'VICTOR MANUEL RUIZ HERNANDEZ', 9864);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4426, 'JOS� LEONEL L�PEZ AJVIX', 5048);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2361, 'CLAUDIA CECILIA CONTRERAS FOLGAR DE ALFARO', 7822);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6139, 'DANIEL EDUARDO VEL�SQUEZ AVILA', 9090);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5422, 'PAMELA  CRISTINA SIKAHALL  URIZAR', 6122);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3194, 'ANGEL DANIEL LOPEZ LOPEZ', 7201);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2945, 'KEWIN MASLOVY PATZ�N TZ�N', 6662);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6656, 'YANIA ESZTER D�VID CADENAS', 6820);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6532, 'VICTOR MANUEL AVILA SARMIENTO', 8042);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7788, 'LUIS MANFREDO REYES CHAVEZ', 8578);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3581, 'CARLOS MANUEL LIMA Y LIMA', 7953);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6560, 'DAVID ESTUARDO MORALES AJCOT', 6231);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3662, 'EDGAR GAMALIEL DE LEON HERNANDEZ', 7286);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7413, 'MANUEL GILBERTO GALVAN ESTRADA', 6296);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9913, 'CARLOS ANIBAL CHICOJAY COLOMA', 5618);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1426, 'JUAN CARLOS MORATAYA RAMOS', 7257);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4884, 'YESSICA ROSMERY CHAMALE NI�OS', 5926);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3140, 'KEVIN JOSU� XILOJ SUBUY�', 6472);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6191, 'CARLOS AUGUSTO MORALES SANTACRUZ', 7879);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1075, 'JULIO  OSWALDO ROJAS  ARGUETA', 5434);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3105, 'CESAR ABIGAIL GARCIA NAJERA', 8770);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8955, 'MARIA EUGENIA AGUILAR BOBADILLA', 9770);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7580, 'CARLOS LEONEL MU�OZ LEMUS', 8615);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9759, 'FRANCISCO JAVIER GARCIA FLORES', 7360);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6264, 'ZULMA KARINA AGUIRRE ORDONEZ', 8827);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5479, 'JAIME HUMBERTO BATTEN ESQUIVEL', 9401);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9912, 'CARLOS ENRIQUE CHICOL CABRERA', 5565);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1316, 'MARILYN CARIBEL ROJAS MALDONADO', 8592);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8491, 'GERARDO RENE ROBLES ALFONSO', 6423);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3051, 'MARIO RENE DE LEON GARCIA', 8211);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7566, 'CARLOS MATIAS CASTELLANOS ARGUIJO', 7767);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2973, 'RAFAEL ENRIQUE MORALES OCHOA', 7601);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4792, 'MARLON ANTONIO PEREZ TURK', 8384);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5666, 'FERNANDO ALFREDO MOSCOSO LIRA', 8235);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5426, 'MARIO RODOLFO CORZO AVILA', 5022);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7262, 'OMAR GILBERTO FLORES BELTETON', 9934);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1438, 'JAVIER ANDR�S VALDEZ GONZ�LEZ', 9839);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7517, 'JORGE ALEJANDRO AREVALO VALDEZ', 9433);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8806, 'MIGUEL ANGEL CANCINOS RENDON', 8805);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8826, 'WILLIAM ALEXANDER SANTOS COLINDRES', 6348);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1619, 'MARIO RENE SANTIZO CALDERON', 5680);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2159, 'EDUARDO ISA� AJSIVINAC XICO', 5497);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1844, 'JOS� LUIS MEND�ZA ALVARADO', 6610);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8331, 'DIEGO ISRAEL NAVARRO GODINEZ', 8100);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1196, 'FRANCISCO ARTURO HERNANDEZ ARRIAZA', 7722);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1442, 'OMAR ALEJANDRO VIDES ESTEBAN', 9250);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9526, 'JEREMY EMMANUEL BARRIOS ARANA', 8721);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1153, 'VICTOR RONALDO G�MEZ LARA', 5048);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2382, 'RUBEN ALEJANDRO RALDA MEJIA', 9361);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8916, 'GERHARD BENJAMIN ARD�N VALD�Z', 9204);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5706, 'MOISES ANTONIO CONDE HERNANDEZ', 8382);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9660, 'JOSE ANTONIO CAMBARA GODOY', 8109);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6645, 'LUIS EDUARDO DE LE�N PACHECO', 9055);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5305, 'PAOLA MISHELLE. HENGSTENBERG PRERA', 8778);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9785, 'ANDRES MANUEL REMIS SALGUERO', 9855);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9694, 'NICOLAS DE JESUS GUZMAN SAENZ', 5683);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6112, 'RENALDO GIRON ALVARADO', 6922);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8251, 'PEDRO PABLO GUZMAN MILIAN', 5382);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2464, 'JORGE EMILIO GODINEZ LEMUS', 8840);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7331, 'JONATHAN ALEXANDER AJBAL CHEGUEN', 7772);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7213, 'JUAN CARLOS JEREZ  JUAREZ', 7028);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2667, 'JUAN MERCK COS', 8689);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3795, 'CINTHYA PATRICIA ORTIZ QUIROA', 5712);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6097, 'SURIEL CRISTINA ABALLI HERWING', 5997);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3583, 'PABLO RODOLFO ZU�IGA RAMIREZ', 9776);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1937, 'EMILIO VLADIMIR LUX MONROY', 6509);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3391, 'EDGAR JOSIAS CAN AJQUEJAY', 6917);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1698, 'CESAR ALFONSO GARCIA GUERRA', 9693);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5896, 'ELSA MARIA ALVARADO JURADO', 6222);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8598, 'V�CTOR REN� P�REZ MAY�N', 6533);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1656, 'ROBERTO GUZMAN ORTIZ', 8937);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6360, 'LUIS CARLOS BOLANOS MENDEZ', 8624);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8380, 'SELVIN ESTUARDO JOACHIN JUAREZ', 8349);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9278, 'RONY OMAR MIGUEL LOPEZ', 5976);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7991, 'EVELYN CAROLINA MORALES RUIZ', 5761);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6241, 'ANGEL ROBERTO SIC GARCIA', 5858);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9739, 'ALBA MARITZA GUERRERO SPINOLA', 6268);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2987, 'LUIS FERNANDO FALLA GUZM�N', 9553);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2298, 'HELEN YESSENIA ESCOBAR RAMOS', 7051);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3264, 'CARLOS FERNANDO PAREDES V�LIZ', 8989);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6810, 'NORMA ILEANA SARMIENTO ZECENA', 7629);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4884, 'MARIA MARTHA WOLFORD E. DE HERNANDEZ', 7735);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1220, 'ROSA EMILIA BOCHE NAZ', 8783);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7205, 'FRANCISCO JAVIER GONZALEZ LOPEZ', 8188);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (2342, 'MARLON FRANCISCO ORELLANA LOPEZ', 9024);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8263, 'RODOLFO ALEXANDER P�REZ TEPEQUE', 7657);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5633, 'JORGE MARIO ESTRADA ASTURIAS', 9975);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6884, 'JOSUE DANIEL SOLIS OSORIO', 5008);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7813, 'SERGIO SAUL RALDA MEJIA', 6716);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (4015, 'LIDIA VALENTINA J�COME CUC�', 8643);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3194, 'KARLA LIZBETH MART�NEZ VARGAS', 7904);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (3805, 'HILDA MYRIAM M�NDEZ CASTILLO DE AVILA', 5642);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9482, 'EDWIN ADALBERTO BRACAMONTE OROZCO', 6462);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (8598, 'ARMANDO ALONSO RIVERA CARRILLO', 6042);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9141, 'HECTOR FRANCISCO REYES FRANCO', 6566);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7335, 'ERICK ESTUARDO HERNANDEZ GARCIA', 7857);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5236, 'LUIS ANGEL AGUILAR CHAMALE', 6027);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9280, 'BYRON GIOVANNI PALACIOS COLINDRES', 7117);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (1517, 'EVEREST DARWIN MEDINILLA RODRIGUEZ', 5519);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (6482, 'PAOLA JUDITH P�REZ URQUIZ�', 6388);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (5724, 'OTTO RENE ESCOBAR LEIVA', 8742);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9583, 'DILAN CONAHER SUY MIRANDA', 5857);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (9466, 'FERNANDO JOSE VICENTE VELASQUEZ', 5937);
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, SUELDO_MENSUAL) VALUES (7677, 'GUILLERMO FRANCISCO MELINI SALGUERO', 7493);

SELECT * FROM docente;

INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0653, 'INGENIERIA DE COSTOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0107, 'AREA MATEMATICA INTERMEDIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0220, 'ANALISIS DE SISTEMAS DE POTENCIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0511, 'MANTENIMIENTO DE HOSPITALES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0349, 'QUIMICA PARA INGENIERIA CIVIL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0232, 'ELECTRONICA  1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0009, 'IDIOMA TECNICO 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0173, 'ANALISIS MECANICO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0200, 'INGENIERIA ELECTRICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3657, 'ADMINISTRACION DE EMPRESAS 2 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0084, 'TOPOGRAFIA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0348, 'QUIMICA GENERAL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0234, 'ELECTRONICA 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2013, 'PRACTICAS FINALES INGENIERIA ELECTRONICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0482, 'OPERACIONES Y PROCESOS EN LA INDUSTRIA FARMACEUTICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0390, 'TERMODINAMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0090, 'PROGRAMACION DE COMPUTADORAS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0394, 'TERMODINAMICA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0674, 'FUNDAMENTOS DE MERCADOTECNIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2025, 'PRACTICAS INICIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0212, 'CONVERSION DE ENERGIA ELECTROMECANICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0970, 'REDES DE COMPUTADORAS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0249, 'ELECTRONICA 6');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0358, 'QUIMICA ORGANICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0662, 'LEGISLACION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0222, 'PROTECCION DE SISTEMAS DE POTENCIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0608, 'INTROD DE PROYECTOS GERENCIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0285, 'SISTEMAS OPERATIVOS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0208, 'INSTALACIONES ELECTRICAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0236, 'SISTEMAS DE CONTROL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0732, 'ESTADISTICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0991, 'LENGUAJES DE PROGRAMACION APLICADOS A I.E.');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0014, 'ECONOMIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0454, 'METALURGIA Y METALOGRAFIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3658, 'ADMINISTRACION DE PERSONAL (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0786, 'SISTEMAS ORGANIZACIONALES Y GERENCIALES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0434, 'PROCESOS QUIMICOS INDUSTRIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0082, 'TOPOGRAFIA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0798, 'SEMINARIO DE SISTEMAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0073, 'DIBUJO TECNICO MECANICO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0550, 'VIAS TERRESTRES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0414, 'IQ-3 TRANSFERENCIA DE CALOR');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5012, 'COMUNICACION Y REDACCION I');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0630, 'INGENIERIA DE LA PRODUCCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0006, 'IDIOMA TECNICO 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0799, 'SEMINARIO DE INVESTIGACION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0968, 'INTELIGENCIA ARTIFICIAL 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2004, 'PRACTICAS FINALES INGENIERIA ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0018, 'FILOSOFIA DE LA CIENCIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0314, 'CONCRETO ARMADO 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0436, 'DISE\O DE EQUIPO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1071, 'DIPLOMADO MANTENIMIENTO INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0638, 'CONTROLES INDUSTRIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0210, 'TEORIA ELECTROMAGNETICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0778, 'ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7987, 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0060, 'TALLER DE SIST DE INF GEOGRAFICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0307, 'TIPOLOGIA ESTRUCTURAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0771, 'INTRODUCCION A LA PROGRAMACION Y COMPUTACION 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0659, 'ADMINISTRACION DE RECURSOS HUMANOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0352, 'QUIMICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0657, 'ADMINISTRACION DE EMPRESAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3120, 'MATEMATICA APLICADA 2 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0346, 'METODOS DE CONSTRUCCION Y SUPERVISION DE OBRAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1077, 'DIPLOMADO EN RECURSOS HUMANOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0388, 'LABORATORIO DE FISICO QUIMICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0288, 'INTRODUCCION AL ESTUDIO DE IMPACTO AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0560, 'VIAS TERRESTRES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0216, 'SUBESTACIONES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0708, 'PREPARACION Y EVALUACION DE PROYECTOS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0524, 'DISE\O DE MAQUINAS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0632, 'INGENIERIA DE PLANTAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3116, 'MATEMATICA APLICADA 3 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0204, 'CIRCUITOS ELECTRICOS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0281, 'SISTEMAS OPERATIVOS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0011, 'IDIOMA TECNICO 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7988, 'SEMINARIO DE INVESTIGACION E.P.S. ELECTRONICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1023, 'DIPLOMADO EN ACONDICIONAMIENTO DEL AGUA EN LA INDUSTRIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0150, 'FISICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0687, 'GEOLOGIA ESTRUCTURAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0585, 'INGENIERIA DE TRANSITO Y TRANSPORTES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0017, 'AREA SOCIAL HUMANISTICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0030, 'GEOGRAFIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0620, 'GESTION AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0672, 'FUNDAMENTOS DE ADMINISTRACION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0642, 'SEGURIDAD E HIGIENE INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0655, 'ADMINISTRACION FINANCIERA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0069, 'AREA TECNICA COMPLEMENTARIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0322, 'DISE\O ESTRUCTURAL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0606, 'ANALISIS DE SISTEMAS INDUSTRIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0972, 'INTELIGENCIA ARTIFICIAL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0214, 'MAQUINAS ELECTRICAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3123, 'MATEMATICA APLICADA 5 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7981, 'SEMINARIO DE INVESTIGACION E.P.S. CIVIL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0450, 'GEOLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1056, 'DIPLOMADO SEGURIDAD INDUSTRIAL Y SALUD OCUPACIONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0777, 'ORGANIZACION DE LENGUAJES Y COMPILADORES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0636, 'DISE\O PARA LA PRODUCCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3664, 'LEGISLACION 2 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0643, 'SALUD Y SEGURIDAD OCUPACIONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2035, 'PRACTICAS FINALES INGENIERIA AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0416, 'IQ-4 TRANSFERENCIA DE MASA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1059, 'DIPLOMADO BUENAS PRACTICAS DE MAN EN LA IND FARMA Y ALIMENTICIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0245, 'COMUNICACIONES 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2002, 'PRACTICAS FINALES INGENIERIA QUIMICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1100, 'DIPLOMADO GESTION INMOBILIARIA, TENDENCIAS CONSTRUCTIVAS Y PLANIFICACION TERRITORIAL EN GUATEMALA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0700, 'INGENIERIA ECONOMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0504, 'MOTORES DE COMBUSTION INTERNA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0028, 'ECOLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5011, 'FUNDAMENTOS JURIDICOS CONSTITUCIONALES BASICOS DEL DERECHO LABORAL Y NORMAS LABORALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7904, 'SEMINARIO DE INVESTIGACION ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0221, 'SISTEMAS DE GENERACION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0092, 'PROGRAMACION DE COMPUTADORAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0289, 'INTRODUCCION A LA INGENIERIA AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7999, 'SEMINARIO DE INVESTIGACION E.P.S. SISTEMAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0772, 'ESTRUCTURAS DE DATOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0262, 'AGUAS SUBTERRANEAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0371, 'INTRODUCCION A LA INGENIERIA QUIMICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3669, 'ECONOMIA INDUSTRIAL (DIPLOMADO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0658, 'ADMINISTRACION DE PERSONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0362, 'ANALISIS CUALITATIVO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0074, 'DIBUJO CONSTRUCTIVO PARA INGENIERIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7913, 'SEMINARIO DE INVESTIGACION ELECTRONICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0528, 'DISE\O DE MAQUINAS 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1093, 'DIPLOMADO ESTRATEGIAS DE LECTURA PARA UNA COMPRENSION ANALITICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0202, 'INGENIERIA ELECTRICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0152, 'FISICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0240, 'ELECTRONICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2003, 'PRACTICAS FINALES INGENIERIA MECANICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7995, 'SEMINARIO DE INVESTIGACION MECANICA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3022, 'PSICOLOGIA INDUSTRIAL (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0209, 'INSTALACION DE EQUIPOS ELECTRONICOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0969, 'TELECOMUNICACIONES Y REDES LOCALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0392, 'TERMODINAMICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0412, 'FLUJO DE FLUIDOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (9000, 'P.A.P. DE MATEMATICA PARA INGENIERIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0644, 'INGENIERIA TEXTIL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0787, 'SISTEMAS ORGANIZACIONALES Y GERENCIALES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7991, 'SEMINARIO DE INVESTIGACION CIVIL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0785, 'ANALISIS Y DISE\O DE SISTEMAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0122, 'MATEMATICA APLICADA 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1060, 'DIPLOMADO CADENA DE SUMISTROS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0211, 'TEORIA ELECTROMAGNETICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0354, 'QUIMICA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3662, 'LEGISLACION 1 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0282, 'INGENIERIA SANITARIA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0455, 'MATERIALES DE CONSTRUCCION 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0311, 'ANALISIS ESTRUCTURAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1094, 'DIPLOMADO ELABORACION, FORMULACION Y EVALUACION DE PROYECTOS DE INVERSION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0458, 'MECANICA DE SUELOS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0170, 'MECANICA ANALITICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0781, 'ORGANIZACION DE LENGUAJES Y COMPILADORES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0512, 'INSTRUMENTACION MECANICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0506, 'PLANTAS DE VAPOR');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0722, 'TEORIA DE SISTEMAS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0147, 'FISICA BASICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0368, 'PRINCIPIOS DE METROLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7986, 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0634, 'INGENIERIA DE METODOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0652, 'CONTABILIDAD 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5003, 'DIBUJO TECNICO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0665, 'MICROECONOMIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1084, 'DIPLOMADO DE PROPIEDAD INTELECTUAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7989, 'SEMINARIO DE INVESTIGACION E.P.S. AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0418, 'IQ-5 TRANSFERENCIA DE MASA EN UNIDADES CONTINUAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0513, 'MANTENIMIENTO DE HOSPITALES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0476, 'GEOLOGIA DEL PETROLEO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0526, 'DISE\O DE MAQUINAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7935, 'SEMINARIO DE INVESTIGACION AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0669, 'ECONOMIA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0103, 'AREA MATEMATICA BASICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0428, 'LABORATORIO DE INGENIERIA QUIMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0246, 'ELECTRONICA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2001, 'PRACTICAS FINALES INGENIERIA CIVIL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0280, 'INGENIERIA SANITARIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0780, 'SOFTWARE AVANZADO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0980, 'PROYECTOS DE COMPUTACION APLICADA A I.E.');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0332, 'PUENTES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0112, 'AREA MATEMATICA INTERMEDIA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0768, 'INTRODUCCION A LOS ALGORITMOS Y FLUJO DE DATOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2006, 'PRACTICAS FINALES INGENIERIA MECANICA ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1025, 'DIPLOMADO EN ADMINISTRACION DE LA CALIDAD');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0975, 'REDES DE COMPUTADORAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0252, 'HIDRAULICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0667, 'PROGRAMACION COMERCIAL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0423, 'EXTRACCIONES INDUSTRIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0639, 'CONTROL ESTADISTICO DE LA CALIDAD');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0601, 'INVESTIGACION DE OPERACIONES I');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0770, 'INTRODUCCION A LA PROGRAMACION Y COMPUTACION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0219, 'TRANSMISION Y DISTRIBUCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0235, 'ROBOTICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1076, 'DIPLOMADO EN GESTION GERENCIAL DE OPERACIONES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0795, 'LOGICA DE SISTEMAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0213, 'CONVERSION DE ENERGIA ELECTROMECANICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0666, 'COSTOS PRESUPUESTOS Y AVALUOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0676, 'COMERCIO INTERNACIONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0254, 'HIDROLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0008, 'IDIOMA TECNICO 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0154, 'FISICA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0409, 'SEPARACION POR MEDIO DE MEMBRANAS SELECTIVAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3606, 'ANALISIS DE SISTEMAS INDUSTRIALES (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0452, 'CIENCIA DE LOS MATERIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0796, 'LENGUAJES FORMALES Y DE PROGRAMACION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0366, 'ANALISIS INSTRUMENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0224, 'ALTA TENSION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0361, 'BIOQUIMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0610, 'INFORMATICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0370, 'QUIMICA AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0005, 'TECNICAS DE ESTUDIO E INVESTIGACION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0433, 'INGENIERIA DEL AZUCAR');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0356, 'QUIMICA 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0472, 'TECNOLOGIA DE LOS ALIMENTOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0650, 'CONTABILIDAD 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0769, 'INTRODUCCION A LA PROGRAMACION DE COMPUTADORAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0663, 'LEGISLACION AMBIENTAL 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0660, 'MERCADOTECNIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0248, 'ELECTRONICA 5');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0201, 'INSTALACIONES ELECTRICAS (CIVIL)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0382, 'FISICO QUIMICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0462, 'ELECTRICIDAD Y ELECTRONICA BASICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0196, 'CALIDAD DEL AIRE');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0410, 'BALANCE DE MASA Y ENERGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0118, 'MATEMATICA APLICADA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0241, 'RADIOCOMUNICACIONES TERRESTRES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0710, 'PLANEAMIENTO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0704, 'INGENIERIA ECONOMICA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0318, 'CIMENTACIONES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0218, 'LINEAS DE TRANSMISION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0238, 'AUTOMATIZACION INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0962, 'MATEMATICA PARA COMPUTACION 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0964, 'ORGANIZACION COMPUTACIONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2005, 'PRACTICAS FINALES INGENIERIA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5015, 'ALBA�ILERIA PRACTICA PARA CONOCER LAS TECNICAS DE CONSTRUCCION Y COMO APLICARLAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0120, 'MATEMATICA APLICADA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2009, 'PRACTICAS FINALES INGENIERIA CIENCIAS Y SISTEMAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7984, 'SEMINARIO DE INVESTIGACION E.P.S. ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0156, 'FISICA 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0172, 'MECANICA ANALITICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2036, 'PRACTICAS INTERMEDIAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0440, 'MICROBIOLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0335, 'GESTION DE DESASTRES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0302, 'RESISTENCIA DE MATERIALES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0398, 'CINETICA DE PROCESOS QUIMICOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0664, 'LEGISLACION 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0453, 'MATERIALES DE CONSTRUCCION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0432, 'DINAMICA DE PROCESOS QUIMICOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7980, 'INVESTIGACION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0198, 'CALIDAD DEL AGUA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0114, 'AREA MATEMATICA INTERMEDIA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0724, 'TEORIA DE SISTEMAS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0775, 'SISTEMAS DE BASES DE DATOS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0316, 'CONCRETO ARMADO 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0437, 'CONTROL DE CONTAMINANTES INDUSTRIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0244, 'COMUNICACIONES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0637, 'DISE�O INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1074, 'DIPLOMADO EN LIDERAZGO DEL TALENTO HUMANO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0089, 'COMUNICACION ASERTIVA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1065, 'DIPLOMADO ADMINISTRACION Y COMPETENCIAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0532, 'VIBRACIONES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0022, 'PSICOLOGIA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0396, 'TERMODINAMICA 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0779, 'ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0960, 'MATEMATICA PARA COMPUTACION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7905, 'SEMINARIO DE INVESTIGACION INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0300, 'RESISTENCIA DE MATERIALES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0640, 'CONTROL DE LA PRODUCCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0774, 'SISTEMAS DE BASES DE DATOS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0442, 'BIOINGENIERIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3710, 'PLANEAMIENTO (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0421, 'GESTION TOTAL DE LA CALIDAD');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5010, 'SEGURIDAD EN LAS OBRAS DE CONSTRUCCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0283, 'ANALISIS Y DISE\O DE SISTEMAS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0614, 'LOGISTICA Y CADENA DE SUMINISTRO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0603, 'INVESTIGACION DE OPERACIONES II');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0720, 'MODELACION Y SIMULACION 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0380, 'FISICO QUIMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7993, 'SEMINARIO DE INVESTIGACION MECANICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0243, 'COMUNICACIONES 4');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0101, 'AREA MATEMATICA BASICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0460, 'PAVIMENTOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0486, 'DISE\O DE PLANTAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1101, 'GESTION DE PERSONAL EN LA ADMINISTRACION PUBLICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0242, 'COMUNICACIONES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1091, 'DIPLOMADO DESARROLLO DE PRACTICAS EMPRESARIALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7985, 'SEMINARIO DE INVESTIGACION E.P.S. INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0019, 'AREA SOCIAL HUMANISTICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0123, 'MATEMATICA APLICADA 5');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0039, 'DEPORTES 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (1034, 'DIPLOMADO EN ADMINISTRACION DE LA CALIDAD EN LA INDUSTRIA ALIMENTICIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0233, 'ELECTRONICA APLICADA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7982, 'SEMINARIO DE INVESTIGACION E.P.S. QUIMICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5014, 'PRINCIPIOS BASICOS DE OBRAS DE CONSTRUCCION');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0773, 'MANEJO E IMPLEMENTACION DE ARCHIVOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3656, 'ADMINISTRACION DE EMPRESAS 1 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0510, 'INSTALACIONES MECANICAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0001, 'ETICA PROFESIONAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0734, 'ESTADISTICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5007, 'COMUNICACION Y REDACCION II');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7994, 'SEMINARIO DE INVESTIGACION MECANICA ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0502, 'REFRIGERACION Y AIRE ACONDICIONADO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0430, 'LABORATORIO DE INGENIERIA QUIMICA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0324, 'DISE\O ESTRUCTURAL 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0712, 'URBANISMO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0116, 'MATEMATICA APLICADA 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0250, 'MECANICA DE FLUIDOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0027, 'BIOLOGIA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0508, 'MONTAJE Y MANTENIMIENTO DE EQUIPO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (2007, 'PRACTICAS FINALES INGENIERIA MECANICA INDUSTRIAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0654, 'CONTABILIDAD 3');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0522, 'PROCESOS DE MANUFACTURA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7902, 'SEMINARIO DE INVESTIGACION QUIMICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (7983, 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0258, 'MAQUINAS HIDRAULICAS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0080, 'TOPOGRAFIA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0230, 'INSTRUMENTACION ELECTRICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (3118, 'MATEMATICA APLICADA 1 (DIPLOMADO)');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0706, 'PREPARACION Y EVALUACION DE PROYECTOS 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0286, 'HIDRAULICA DE CANALES');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0797, 'SEMINARIO DE SISTEMAS I');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (5008, 'ARITMETICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0386, 'LABORATORIO DE FISICO QUIMICA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0729, 'MODELACION Y SIMULACION 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0284, 'SANEAMIENTO AMBIENTAL');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0320, 'CIMENTACIONES 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0530, 'MECANISMOS');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0736, 'ANALISIS PROBABILISTICO');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0520, 'PROCESOS DE MANUFACTURA 1');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0239, 'ELECTRONICA APLICADA 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0206, 'CIRCUITOS ELECTRICOS 2');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0612, 'GESTION TECNOLOGICA');
INSERT INTO CURSO (ID_CURSO, NOMBRE) VALUES (0656, 'ADMINISTRACION DE EMPRESAS 1');

SELECT * FROM CURSO;

INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (1, 'S-12');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (2, 'S-11');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (3, 'MEET');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (4, 'EXT');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (5, '0000');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (6, 'T-3');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (7, 'T-1');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (8, 'T-5');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (9, 'EPS');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (10, 'ET');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (11, 'T-7');
INSERT INTO EDIFICIO (ID_EDIFICIO, NOMBRE) VALUES (12, 'HIBR');

SELECT * FROM EDIFICIO;