-- ============================================================
-- DROP ALL TABLES
-- ============================================================
DROP TABLE ASIGNACION CASCADE CONSTRAINTS;
DROP TABLE PENSUM CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE DOCENTE CASCADE CONSTRAINTS;
DROP TABLE CURSO CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO CASCADE CONSTRAINTS;
DROP TABLE SALON CASCADE CONSTRAINTS;
DROP TABLE PERIODO CASCADE CONSTRAINTS;
DROP TABLE DIA CASCADE CONSTRAINTS;
DROP TABLE JORNADA CASCADE CONSTRAINTS;
DROP TABLE UNIDAD_ACADEMICA CASCADE CONSTRAINTS;
DROP TABLE PLAN CASCADE CONSTRAINTS;
DROP TABLE SECCION CASCADE CONSTRAINTS;
DROP TABLE INSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE CARRERA CASCADE CONSTRAINTS;
DROP TABLE PRERREQUISITO CASCADE CONSTRAINTS;
DROP TABLE HORARIO CASCADE CONSTRAINTS;

-- ============================================================
-- DROP ALL INDEXES
-- ============================================================
ALTER TABLE UNIDAD_ACADEMICA
DROP CONSTRAINT UNIDAD_ACADEMICA_PK;

-- ============================================================
-- DROP ALL DISPARADORES
-- ============================================================
DROP TRIGGER TRG_UNIDAD_ACADEMICA;

-- ============================================================
-- DROP ALL SECUENCIAS
-- ============================================================
DROP SEQUENCE SEQ_UNIDAD_ACADEMICA;
DROP SEQUENCE UNIDAD_ACADEMICA_ID_UNIDAD_A;