-- UNIDAD ACADEMICA
INSERT ALL
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (1, 'Escuela Técnica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (2, 'Escuela de Estudios de Postgrado')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (3, 'Escuela de Ciencias')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (4, 'Escuela de Ingeniería Civil')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (5, 'Escuela de Ingeniería Química')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (6, 'Escuela de Ingeniería Mecánica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (7, 'Escuela de Ingeniería Mecánica Eléctrica')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (8, 'Escuela de Ingeniería Mecánica Industrial')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (9, 'Escuela de Ingeniería en Industrias Agropecuarias y Forestales')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (10, 'Escuela de Ingeniería en Ciencias y Sistemas')
    INTO UNIDAD_ACADEMICA (ID_UNIDAD_A, NOMBRE) VALUES (11, 'Escuela Regional de Ingeniería Sanitaria y Recursos Hidráulicos - ERIS')
SELECT 1 FROM DUAL;

SELECT * FROM unidad_academica;

-- CARRERAS FACULTAD INGENIERI
INSERT ALL
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (1, 'Ingeniería Civil', 4)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (2, 'Ingeniería Química', 5)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (3, 'Ingeniería Mecánica', 6)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (4, 'Ingeniería Eléctrica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (5, 'Ingeniería Industrial', 8)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (6, 'Ingeniería Mecánica Eléctrica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (7, 'Ingeniería Mecánica Industrial', 8)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (9, 'Ingeniería en Ciencias y Sistemas', 10)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (13, 'Ingeniería Electrónica', 7)
    INTO CARRERA (ID_CARRERA, NOMBRE, UNIDAD_ACADEMICA_ID_UNIDAD_A) VALUES (35, 'Ingeniería Ambiental', 5)
SELECT 1 FROM DUAL;

SELECT * FROM carrera;