CREATE TABLE RIMAES_REPORT (
    RIMA_EMPRESA_REMESADORA   VARCHAR2(4 BYTE), 
	RIMA_NUMERO_TRANSFERENCIA VARCHAR2(20 BYTE), 
	RIMA_NOMBRE_BENEFICIARIO  VARCHAR2(150 BYTE), 
	RIMA_NOMBRE_REMITENTE VARCHAR2(150 BYTE), 
	RIMA_DIRECC_BENEFICIARIO VARCHAR2(80 BYTE), 
	RIMA_PAIS_ORDENANTE VARCHAR2(50 BYTE), 
	RIMA_ESTADO_ORDENANTE VARCHAR2(20 BYTE), 
	RIMA_CIUDAD_ORDENANTE VARCHAR2(70 BYTE), 
	RIMA_CANTIDAD_A_PAGAR VARCHAR2(19 BYTE), 
	RIMA_FECHA_INSERCION VARCHAR2(8 BYTE), 
	RIMA_STATUS_BI VARCHAR2(2 BYTE), 
	RIMA_ID_SEC_AGENTE_PAGA VARCHAR2(8 BYTE), 
	RIMA_TELEFO_BENEFICIARIO VARCHAR2(40 BYTE), 
	RIMA_HORA_BI VARCHAR2(6 BYTE), 
	RIMA_MONEDA_PAGO VARCHAR2(3 BYTE), 
	RIMA_MONTO_ORIGINAL VARCHAR2(19 BYTE), 
	RIMA_STATUS_REG_EMPRESA VARCHAR2(2 BYTE), 
	RIMA_NOMBRE_BANCO VARCHAR2(10 BYTE), 
	CONSTRAINT PK_RIMAES_REPORT PRIMARY KEY (RIMA_EMPRESA_REMESADORA, RIMA_NUMERO_TRANSFERENCIA)
);

CREATE TABLE RIJRHI_REPORTE (
    RIHI_EMPRESA VARCHAR2(4 BYTE), 
	RIHI_ID_REMESA VARCHAR2(20 BYTE), 
	RIHI_SECUENCIA_HOST VARCHAR2(6 BYTE), 
	RIHI_FECHA_PAGO VARCHAR2(10 BYTE), 
	RIHI_CLIENTE_FREC VARCHAR2(20 BYTE), 
	RIHI_AGENCIA VARCHAR2(120 BYTE), 
	RIHI_DOC_ID_PAG_A VARCHAR2(120 BYTE), 
	RIHI_NO_CTA_DEPOSITO VARCHAR2(80 BYTE), 
	RIHI_USUARIO VARCHAR2(50 BYTE), 
	RIHI_NUMERO_AUTORIZ VARCHAR2(20 BYTE), 
	RIHI_CONCESIONARIO VARCHAR2(70 BYTE), 
	RIHI_TERMINAL VARCHAR2(19 BYTE), 
	CONSTRAINT PK_RIJRHI_REPORT PRIMARY KEY (RIHI_EMPRESA, RIHI_ID_REMESA)
);

-- LLave foranea para RIJRHI_REPORTE a RIMAES_REPORT
ALTER TABLE RIJRHI_REPORTE
ADD CONSTRAINT FK_RIJRHI_RIMAES FOREIGN KEY (RIHI_EMPRESA, RIHI_ID_REMESA)
REFERENCES RIMAES_REPORT (RIMA_EMPRESA_REMESADORA, RIMA_NUMERO_TRANSFERENCIA);

