-- ============================================================
-- TABLA: UNIDAD_ACADEMICA
-- Descripción: Unidades académicas de la Facultad de Ingeniería
--              (ej. Escuela de Ciencias y Sistemas, EQUI, ECIV)
--              Una UNIDAD_ACADEMICA agrupa una o más CARRERAS.
-- Dependencias: Ninguna (tabla padre)
-- Debe crearse ANTES que: CARRERA
-- ============================================================

CREATE TABLE UNIDAD_ACADEMICA (
    ID_UNIDAD_A  INTEGER         GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE       VARCHAR2(100)   NOT NULL,
    -- --------------------------------------------------------
    CONSTRAINT PK_UNIDAD_ACADEMICA PRIMARY KEY (ID_UNIDAD_A),
    CONSTRAINT UQ_UNIDAD_ACADEMICA_NOMBRE UNIQUE (NOMBRE)
);

-- Datos semilla
INSERT INTO UNIDAD_ACADEMICA (NOMBRE) VALUES ('Escuela de Ciencias y Sistemas');
INSERT INTO UNIDAD_ACADEMICA (NOMBRE) VALUES ('Escuela de Ingeniería Civil');
INSERT INTO UNIDAD_ACADEMICA (NOMBRE) VALUES ('Escuela de Ingeniería Mecánica');
INSERT INTO UNIDAD_ACADEMICA (NOMBRE) VALUES ('Escuela de Ingeniería Química');
INSERT INTO UNIDAD_ACADEMICA (NOMBRE) VALUES ('Escuela de Ingeniería Mecánica Industrial');

-- Verificación
SELECT * FROM UNIDAD_ACADEMICA;
