-- ? Crear Tabla Centro
/*
* La tabla Centro almacena información sobre los centros de evaluación.
* Campos:
* - ID_CENTRO: Identificador único del centro (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - NOMBRE: Nombre del centro (único y no nulo), no debe duplicarse
*   en la tabla Centro.
* Restricciones:
* - La columna ID_CENTRO es una clave primaria que se genera 
*   automáticamente.
* - La columna NOMBRE debe ser única y no puede ser nula.
*/
CREATE TABLE CENTRO
(
    ID_CENTRO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CENTRO PRIMARY KEY (ID_CENTRO),
    CONSTRAINT UQ_CENTRO_NOMBRE UNIQUE (NOMBRE)
)

-- ? Insertar datos en la tabla Centro
INSERT INTO CENTRO (NOMBRE) VALUES ('CENTRO 1');
INSERT INTO CENTRO (NOMBRE) VALUES ('CENTRO 2');
INSERT INTO CENTRO (NOMBRE) VALUES ('CENTRO 3');
INSERT INTO CENTRO (NOMBRE) VALUES ('CENTRO 4');
INSERT INTO CENTRO (NOMBRE) VALUES ('CENTRO 5');

-- ? Insertar un nuevo centro con un ID_CENTRO específico
INSERT INTO CENTRO (ID_CENTRO, NOMBRE) VALUES (6, 'CENTRO 6');

-- ? Reiniciar el contador en el valor maximo actual ++1.
/*
* Corrige el desfase depués de una inserción manual de un ID_CENTRO específico.
* START WITH se utiliza para establecer el valor incial del contador de la columna ID_CENTRO.
* validando si este ya fue insertado manualmente, sino se mantiene el valor actual del contador.
*/
ALTER TABLE CENTRO MODIFY ID_CENTRO GENERATED BY DEFAULT 
ON NULL AS IDENTITY (START WITH LIMIT VALUE)

-- ? Eliminar la tabla Centro
/*
* El comando DROP TABLE se utiliza para eliminar la tabla Centro de la base de datos.
* El indice de la tabla Centro se eliminará automáticamente al eliminar la tabla.
* a diferencia de TRUNCATE TABLE, DROP TABLE elimina la estructura de la tabla y sus datos,
* mientras que TRUNCATE TABLE solo elimina los datos pero mantiene la estructura de la tabla.
*/
DROP TABLE CENTRO;

-- ? Consultar datos de la tabla Centro
SELECT * FROM CENTRO;