-- ? Crea tabla Correlativo
/*
* La tabla Correlativo se utiliza para almacenar información sobre los correlativos de los exámenes realizados.
* Campos:
* - ID_CORRELATIVO: Identificador único del correlativo (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - FECHA: Fecha en que se realizó el examen (no nulo).
* - NO_EXAMEN: Número de examen asociado al correlativo (no nulo).
* Relaciones:
* - La tabla CORRELATIVO tiene una relación de clave foránea con la tabla EXAMEN a través del campo NO_EXAMEN.
*/
CREATE TABLE CORRELATIVO
(
    ID_CORRELATIVO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FECHA DATE NOT NULL,
    NO_EXAMEN INTEGER NOT NULL,
    CONSTRAINT PK_CORRELATIVO PRIMARY KEY (ID_CORRELATIVO)
    CONSTRAINT FK_NO_EXAMEN 
            FOREIGN KEY (NO_EXAMEN) 
            REFERENCES EXAMEN(ID_EXAMEN)
);

-- ? Inserta datos en la Tabla Correlativo}
INSERT INTO CORRELATIVO (FECHA, NO_EXAMEN) 
VALUES (TO_DATE('2024-03-13', 'YYYY-MM-DD'), 1);

INSERT INTO CORRELATIVO (FECHA, NO_EXAMEN)
VALUES (TO_DATE('2024-03-14', 'YYYY-MM-DD'), 2);

