-- ? Crea tabla Correlativo
/*
* La tabla Correlativo almacena información sobre los correlativos de los exámenes realizados.
* Campos:
* - ID_CORRELATIVO: Identificador único del correlativo (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - FECHA: Fecha en que se realizó el examen (no nulo).
* - NO_EXAMEN: Número de examen asociado al correlativo (no nulo).
* Relaciones:
* - La tabla CORRELATIVO tiene una relación de clave foránea con la tabla EXAMEN a través del campo NO_EXAMEN.
*/
CREATE TABLE CORRELATIVO
(
    ID_CORRELATIVO INTEGER    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FECHA          DATE       NOT NULL,
    NO_EXAMEN      NUMBER(10) NOT NULL,

    CONSTRAINT PK_CORRELATIVO
        PRIMARY KEY (ID_CORRELATIVO),

    CONSTRAINT UQ_CORRELATIVO_NUMERO
        UNIQUE (NO_EXAMEN)
);

/*
* Al crear la tabla CORRELATIVO, el campo NO_EXAMEN se establece como una clave foránea que hace referencia 
* al campo ID_EXAMEN de la tabla EXAMEN. pero esto asegura que cada valor en NO_EXAMEN debe existir previamente en la tabla EXAMEN,
* Como la tabla EXAMEN no ha sido creada aún, se debe crear la tabla EXAMEN antes de ejecutar el comando para crear la tabla CORRELATIVO.
* Pero la tabla EXAMEN tiene una relación de clave foránea con la tabla CORRELATIVO, lo que crea una dependencia circular entre ambas tablas. 

* Para resolver esta situación, se puede crear la tabla CORRELATIVO sin la restricción de clave foránea inicialmente, 
* luego crear la tabla EXAMEN y finalmente agregar la restricción de clave foránea a la tabla CORRELATIVO.
*/
ALTER TABLE CORRELATIVO
ADD CONSTRAINT FK_NO_EXAMEN 
    FOREIGN KEY (NO_EXAMEN) 
    REFERENCES EXAMEN(ID_EXAMEN);

ALTER TABLE EXAMEN
DROP CONSTRAINT FK_CORRELATIVO_ID_CORRELATIVO;

-- ? Inserta datos en la Tabla Correlativo}
INSERT INTO CORRELATIVO (FECHA, NO_EXAMEN) 
VALUES (TO_DATE('2024-03-13', 'YYYY-MM-DD'), 1);

INSERT INTO CORRELATIVO (FECHA, NO_EXAMEN)
VALUES (TO_DATE('2024-03-14', 'YYYY-MM-DD'), 2);

-- ? Consulta para verificar los datos insertados en la tabla Correlativo
SELECT * FROM CORRELATIVO;