-- ? Crea tabla Escuela
/*
* La tabla ESCUELA almacena información sobre las escuelas en Guatemala

* Campos:
* - ID_ESCUELA: Identificador único de la escuela (clave primaria)
* - NOMBRE: Nombre de la escuela
* - DIRECCION: Dirección física de la escuela
* - ACUERDO: Acuerdo relacionado con la escuela
*/
CREATE TABLE ESCUELA
(
    ID_ESCUELA INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(150) NOT NULL,
    ACUERDO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ESCUELA PRIMARY KEY (ID_ESCUELA)
);

-- ? Insertar datos en la tabla Escuela
INSERT INTO ESCUELA (NOMBRE, DIRECCION, ACUERDO) VALUES ('ESCUELA 1', 'GUATEMALA ZONA 1', 'A-03-2023');
INSERT INTO ESCUELA (NOMBRE, DIRECCION, ACUERDO) VALUES ('ESCUELA 2', 'VILLA NUEVA', 'A-043-2023');
INSERT INTO ESCUELA (NOMBRE, DIRECCION, ACUERDO) VALUES ('ESCUELA 3', 'MESCUINTLA', 'A-152-2023');
