-- ? Crea tabla Preguntas
/*
* La tabla Preguntas almacena información sobre las preguntas de evaluación.
* Campos:
* - PREGUNTA_TEXTO: Identificador único de la pregunta (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - PREGUNTA_TEXTO: Texto de la pregunta (no nulo), Si se puede repetir la pregnta.
* - RESPUESTA: Respuesta correcta a la pregunta (no nulo), valor numérico que representa la opción correcta.
* - RES_1, RES_2, RES_3, RES_4: Opciones de respuesta para la pregunta (pueden ser nulas).
*/
CREATE TABLE PREGUNTAS
(
    ID_PREGUNTA INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PREGUNTA_TEXTO VARCHAR2(255) NOT NULL,
    RESPUESTA  NUMBER(1) NOT NULL,
    RES_1 VARCHAR2(255),
    RES_2 VARCHAR2(255),
    RES_3 VARCHAR2(255),
    RES_4 VARCHAR2(255),
    CONSTRAINT PK_PREGUNTAS PRIMARY KEY (ID_PREGUNTA)
);

-- ? Insertar datos en la tabla Preguntas
/*
* Quoted String Literal alternativa: q'[texto]'
* Se utiliza cuando hay caracteres especiales en el texto que podrían interferir con la sintaxis SQL, 
* como tildes, signos de interrogación, comillas simples, etc.
*/
INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4) 
VALUES (q'[¿A CUANTO ASCIENDE LA MULTA POR NO PORTAR LICENCIA DE CONDUCIR?]', 3, 
        'Q50', 
        'Q100', 
        'Q200', 
        'Q300');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES EL MONTO DE LA MULTA POR TIRAR O LANZAR BASURA U OTROS OBJETOS DESDE UN VEHÍCULO ESTACIONADO O EN MOVIMIENTO?]', 3,
        'Q100', 
        'Q200', 
        'Q300', 
        'Q400');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES EL MONTO DE LA MULTA POR CIRCULAR SIN LUZ BAJA DURANTE EL DÍA?]', 4,
        'Q200', 
        'Q400', 
        'Q500', 
        'Q100');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿EN QUE CASO SE APLICARA MULTA DE DOSCIENTOS QUETZALES?]', 1,
        q'[Por portar las placas de circulación en lugares no autorizados]',
        q'[Por circular en el arcen sin causa justificada]',
        q'[Por realizar carreras en la vía publica]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿EN QUE CASO SE APLICARA MULTA DE QUINIENTOS QUETZALES?]', 3,
        q'[Por retroceder en autopistas y vías rápidas]',
        q'[Por rebasar en lugares prohibidos]',
        q'[Por circular con vehículos de carga en horario restringido]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿EN CUAL DE LOS SIGUIENTES CASOS SE APLICARA MULTA DE CUATROCIENTOS QUETZALES?]', 1,
        q'[Por conducir sin tener licencia]',
        q'[Por no portar licencia de conducir]',
        q'[Por circular en el arcén sin causa justificada]',
        q'[Por estacionarse en lugares prohibidos]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES EL MONTO DE LA MULTA POR ESTACIONAR EL VEHÍCULO  EN UN LUGAR NO PERMITIDO SIMULANDO FALLA MECÁNICA?]', 2,
        'Q50', 
        'Q400', 
        'Q200', 
        'Q100');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES EL MONTO DE LA MULTA POR CIRCULAR EN CONTRA LA VÍA SEÑALIZADA O AUTORIZADA?]', 2,
        'Q400', 
        'Q200', 
        'Q600', 
        'Q100');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES EL MONTO DE LA MULTA POR CONDUCIR CON LICENCIA VENCIDA?]', 2,
        'Q100', 
        'Q300', 
        'Q200', 
        'Q500');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿ES LA MULTA POR NO FACILITAR LA INCORPORACIÓN AL TRANSITO A OTROS VEHÍCULOS?]', 3,
        'Q500', 
        'Q300', 
        'Q100', 
        'Q400');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES LA MULTA POR NO PORTAR EL CINTURÓN DE SEGURIDAD?]', 3,
        'Q50', 
        'Q400', 
        'Q200', 
        'Q300');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES LA MULTA POR NO RESPETAR EL LIMITE DE VELOCIDAD?]', 4,
        'Q100', 
        'Q200', 
        'Q500', 
        'Q300');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿A CUANTO ASCIENDE LA MULTA POR NO PORTAR LICENCIA DE CONDUCIR?]', 3,
        'Q50', 
        'Q100', 
        'Q200', 
        'Q300');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CUAL ES LA MULTA POR NO PORTAR EL EQUIPAMIENTO BÁSICO DE SU VEHÍCULO?]', 2,
        'Q100', 
        'Q200', 
        'Q300', 
        'Q400');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿EL ARCEN ES UNA FRANJA PARALELA A LA CALZADA Y PUEDEN USARLA?]', 2,
        q'[Para rebasar]',
        q'[Los vehículos con alguna emergencia]',
        q'[Estacionarse]',
        q'[Todas son correctas]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿POR REGLA GENERAL ESTA PROHIBIDO?]', 1,
        q'[Bocinarle al automóvil de en frente para apurarlo]',
        q'[Rebasar por el carril izquierdo]',
        q'[Detenerse cuando exista la señal de alto]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿UD. VA MANEJANDO Y EL COPILOTO TIRA BASURA POR LA VENTANA?]', 1,
        q'[Multan al piloto por ser el conductor]',
        q'[Es permitido hacerlo y no multan a nadie]',
        q'[Multan a quien tiro la basura]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿CARRIL QUE SIRVE PARA REALIZAR UN DESVIO EN UNA CALZADA?]', 1,
        q'[Carril auxiliar]',
        q'[Carril de aceleración]',
        q'[Carril de desaceleracion]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿QUE NOS INDICA EL SEMÁFORO EN ROJO?]', 4,
        q'[Continuar la marcha]',
        q'[Aproximación a cruce]',
        q'[Ceder el paso]',
        q'[Detenerse obligatoriamente]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿DE QUE COLOR ESTÁN PINTADAS LAS SEÑALES PREVENTIVAS?]', 2,
        q'[Amarillo y azul]',
        q'[Amarillo y negro]',
        q'[Amarillo y rojo]',
        q'[Amarillo y blanco]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿QUE FUNCIÓN CUMPLE LA LINEA DOBLE AMARILLA PINTADA EN LA CARRETERA?]', 3,
        q'[Divide carriles en un solo sentido]',
        q'[Permite rebasar o adelantar]',
        q'[Divide grupos de carriles que van en diferentes sentido de circulacion]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿DE QUE COLORES ESTÁN PINTADAS LAS SEÑALES CIRCUNSTANCIALES (TEMPORALES)?]', 3,
        q'[Azul, verde y blanco]',
        q'[Blanco,rojo y negro]',
        q'[Naranja]',
        NULL);

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿EN QUE CASO SE APLICAN MULTAS DE Q1,000?]', 1,
        q'[Por faltarle el respeto a la autoridad]',
        q'[Por pasar un semáforo en rojo]',
        q'[Por atropellar un peatón]',
        q'[Todas son correctas]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿QUE ES LA LICENCIA DE CONDUCIR?]', 1,
        q'[Documento que identifica al conductor]',
        q'[Documento de identifica al pasajero]',
        q'[Documento que identifica al vehículo]',
        q'[Ninguna es correcta]');

INSERT INTO PREGUNTAS (PREGUNTA_TEXTO, RESPUESTA, RES_1, RES_2, RES_3, RES_4)
VALUES (q'[¿POR SU PESO COMO SE CLASIFICA UNA MOTOCICLETA?]', 2,
        q'[Pesada]',
        q'[Ligero]',
        q'[Especial]',
        q'[Ninguna es correcta]');