-- ? Crea tabla Registro
/*
* La tabla Registro almacena información sobre los registros de trámites realizados en las escuelas de conducción.
* Campos:
* - ID_REGISTRO: Identificador único del registro (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro. 
* - UBICACION_ESCUELA_ID_ESCUELA: Identificador de la escuela de conducción donde se realizó el trámite (no nulo).
*/
CREATE TABLE REGISTRO
(
    ID_REGISTRO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    UBICACION_ESCUELA_ID_ESCUELA INTEGER NOT NULL,
    UBICACION_CENTRO_ID_CENTRO INTEGER NOT NULL,
    MUNICIPIO_ID_MUNICIPIO INTEGER NOT NULL,
    MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    TIPO_TRAMITE VARCHAR2(50) NOT NULL,
    TIPO_LICENCIA CHAR(1) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(100) NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_REGISTRO)
);