-- ? Crea tabla Examen
/*
* La tabla Examen almacena información sobre los exámenes realizados en las escuelas de conducción.
* Campos:
* - ID_EXAMEN: Identificador único del examen (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - REGISTRO_ID_ESCUELA: Identificador de la escuela de conducción asociada al examen (no nulo).
* - REGISTRO_ID_CENTRO: Identificador del centro de atención asociado al examen
*   (no nulo).
* - REGISTRO_MUNICIPIO_ID_MUNICIPIO: Identificador del municipio
*   asociado al examen (no nulo).
* - REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO: Identificador
*   del departamento asociado al examen (no nulo).
* - REGISTRO_ID_REGISTRO: Identificador del registro asociado al examen (no nulo).
* - CORRELATIVO_ID_CORRELATIVO: Identificador del correlativo asociado al examen (no nulo).
* Relaciones:
* - La tabla EXAMEN tiene una relación de clave foránea con la tabla REGIST
*   O a través de los campos REGISTRO_ID_ESCUELA, REGISTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, 
*   REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO y REGISTRO_ID_REGISTRO.
* - La tabla EXAMEN tiene una relación de clave foránea con la tabla CORREL
*   ATIVO a través del campo CORRELATIVO_ID_CORRELATIVO.
*/
CREATE TABLE EXAMEN (
    ID_EXAMEN                                       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    REGISTRO_ID_ESCUELA                             INTEGER NOT NULL,
    REGISTRO_ID_CENTRO                              INTEGER NOT NULL,
    REGISTRO_MUNICIPIO_ID_MUNICIPIO                 INTEGER NOT NULL,
    REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO INTEGER NOT NULL,
    REGISTRO_ID_REGISTRO                            INTEGER NOT NULL,
    CORRELATIVO_ID_CORRELATIVO                      INTEGER NOT NULL,

    CONSTRAINT PK_EXAMEN
        PRIMARY KEY (ID_EXAMEN),

    CONSTRAINT FK_EXAMEN_REGISTRO
        FOREIGN KEY (REGISTRO_ID_REGISTRO)
        REFERENCES REGISTRO(ID_REGISTRO)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXAMEN_CORRELATIVO
        FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO)
        REFERENCES CORRELATIVO(ID_CORRELATIVO)
        ON DELETE CASCADE,

    CONSTRAINT UQ_EXAMEN_CORRELATIVO
        UNIQUE (CORRELATIVO_ID_CORRELATIVO)
);

-- ? Inserta datos en la tabla Examen
INSERT INTO EXAMEN (
    REGISTRO_ID_ESCUELA,
    REGISTRO_ID_CENTRO,
    REGISTRO_MUNICIPIO_ID_MUNICIPIO,
    REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO,
    REGISTRO_ID_REGISTRO,
    CORRELATIVO_ID_CORRELATIVO
) VALUES (1, 1, 1, 1, 1, 1);

INSERT INTO EXAMEN (
    REGISTRO_ID_ESCUELA,
    REGISTRO_ID_CENTRO,
    REGISTRO_MUNICIPIO_ID_MUNICIPIO,
    REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO,
    REGISTRO_ID_REGISTRO,
    CORRELATIVO_ID_CORRELATIVO
) VALUES (2, 1, 14, 1, 2, 2);

-- ? Consulta para verificar los datos insertados en la tabla Examen
SELECT * FROM EXAMEN;
