-- ? Crea tabla Preguntas_Practico
/*
* La tabla Preguntas_Practico almacena información sobre las preguntas prácticas.
* Campos:
* - ID_PREGUNTA_PRACTICO: Identificador único de la pregunta práctica (clave primaria).
*   descripción: El valor puede ser nulo, si lo es se genera automáticamente.
*   "identity" se utiliza para generar automáticamente un valor único para cada nuevo registro.
* - PREGUNTA_TEXTO: Texto de la pregunta práctica (no nulo).
* - PUNTEO: Punteo asignado a la pregunta práctica (no nulo), valor numérico que representa el puntaje de la pregunta.
*/
CREATE TABLE PREGUNTAS_PRACTICO
(
    ID_PREGUNTA_PRACTICO INTEGER       GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PREGUNTA_TEXTO       VARCHAR2(200) NOT NULL,
    PUNTEO               NUMBER(2)     NOT NULL,

    CONSTRAINT PK_PREGUNTAS_PRACTICO
        PRIMARY KEY (ID_PREGUNTA_PRACTICO),

    CONSTRAINT UQ_PREGUNTAS_PRACTICO_TEXTO
        UNIQUE (PREGUNTA_TEXTO)
);

-- ? Insertar datos en la tabla Preguntas_Practico
INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO) 
VALUES (q'[Abrochó y colocó correctamente cinturón de seguridad]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Arranque en rampa]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Cambio de sentido en espacio limitado]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Realización de zigzag de frente]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Prueba de 3 puntos]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[En paralelo]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Usó y abrochó casco]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Zigzag lento]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Zigzag rápido]', 10);

INSERT INTO PREGUNTAS_PRACTICO (PREGUNTA_TEXTO, PUNTEO)
VALUES (q'[Evitar un obstáculo]', 10);

-- ? Consulta Tabla PREGUNTAS_PRACTICO
SELECT * FROM PREGUNTAS_PRACTICO;